# Generated by Django 5.0 on 2025-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_date_user_is_blocked_user_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saler_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Saler ID'),
        ),
    ]
