# Generated by Django 5.0 on 2025-01-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_saler_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saler_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Saler ID'),
        ),
    ]
