# Generated by Django 5.0 on 2025-01-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_saler_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Client ID'),
        ),
    ]
