# Generated by Django 5.0 on 2025-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yiguvchi',
            field=models.BooleanField(default=False, verbose_name='Yiguvchi'),
        ),
    ]
