# Generated by Django 5.0 on 2025-04-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yiguvchi',
            field=models.BooleanField(default=False, null=True, verbose_name='Tayyorlovchi'),
        ),
    ]
